In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns
import numpy as np

In [2]:
risk = pd.read_csv("../data/UCI_Credit_Card.csv")
risk.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

### PAY LATEST

In [23]:
risk.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default.payment.next.month', 'PAY_LATEST', 'PAY_MEAN', 'PAY_MAX_DELAY',
       'PAY_COUNT_DELAY_1plus', 'PAY_COUNT_DELAY_2plus', 'PAY_TREND',
       'PAY_RATIO_LATEST'],
      dtype='object')

In [3]:
risk["PAY_LATEST"] = risk["PAY_0"]

In [4]:
risk[["PAY_LATEST", "default.payment.next.month"]].head()

   PAY_LATEST  default.payment.next.month
0           2                           1
1          -1                           1
2           0                           0
3           0                           0
4          -1                           0

In [5]:
risk[["PAY_LATEST", "default.payment.next.month"]].corr()

                            PAY_LATEST  default.payment.next.month
PAY_LATEST                    1.000000                    0.324794
default.payment.next.month    0.324794                    1.000000

### PAY MEAN

In [6]:
risk["PAY_MEAN"] = risk[["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]].mean(axis=1)

In [7]:
risk[["PAY_MEAN", "default.payment.next.month"]].head()

   PAY_MEAN  default.payment.next.month
0 -0.333333                           1
1  0.500000                           1
2  0.000000                           0
3  0.000000                           0
4 -0.333333                           0

In [8]:
risk[["PAY_MEAN", "default.payment.next.month"]].corr()

                            PAY_MEAN  default.payment.next.month
PAY_MEAN                    1.000000                    0.281955
default.payment.next.month  0.281955                    1.000000

### PAY MAX DELAY

In [9]:
risk["PAY_MAX_DELAY"] = risk[["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]].max(axis=1)
risk[["PAY_MAX_DELAY", "default.payment.next.month"]].head()

   PAY_MAX_DELAY  default.payment.next.month
0              2                           1
1              2                           1
2              0                           0
3              0                           0
4              0                           0

In [10]:
risk[["PAY_MAX_DELAY", "default.payment.next.month"]].corr()

                            PAY_MAX_DELAY  default.payment.next.month
PAY_MAX_DELAY                    1.000000                    0.331036
default.payment.next.month       0.331036                    1.000000

### PAY_COUNT_DELAY_1plus

In [11]:
risk["PAY_COUNT_DELAY_1plus"] = (risk[["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]] >= 1).sum(axis=1)
risk[["PAY_COUNT_DELAY_1plus", "default.payment.next.month"]].head()

   PAY_COUNT_DELAY_1plus  default.payment.next.month
0                      2                           1
1                      2                           1
2                      0                           0
3                      0                           0
4                      0                           0

In [12]:
risk[["PAY_COUNT_DELAY_1plus", "default.payment.next.month"]].corr()

                            PAY_COUNT_DELAY_1plus  default.payment.next.month
PAY_COUNT_DELAY_1plus                    1.000000                    0.398394
default.payment.next.month               0.398394                    1.000000

### PAY_COUNT_DELAY_2plus

In [13]:
risk["PAY_COUNT_DELAY_2plus"] = (risk[["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]] > 1).sum(axis=1)
risk[["PAY_COUNT_DELAY_2plus", "default.payment.next.month"]].head()

   PAY_COUNT_DELAY_2plus  default.payment.next.month
0                      2                           1
1                      2                           1
2                      0                           0
3                      0                           0
4                      0                           0

In [14]:
risk[["PAY_COUNT_DELAY_2plus", "default.payment.next.month"]].corr()

                            PAY_COUNT_DELAY_2plus  default.payment.next.month
PAY_COUNT_DELAY_2plus                    1.000000                    0.398873
default.payment.next.month               0.398873                    1.000000

### PAY TREND

In [16]:
risk["PAY_TREND"] = risk["PAY_0"] - risk["PAY_6"]

In [17]:
risk[["PAY_TREND", "default.payment.next.month"]].corr()

                            PAY_TREND  default.payment.next.month
PAY_TREND                    1.000000                    0.128774
default.payment.next.month   0.128774                    1.000000

### PAYMENT CAPACITY FEATURES

In [21]:
risk["PAY_RATIO_LATEST"] = np.where(
    risk["BILL_AMT1"] > 0,
    risk["PAY_AMT1"] / risk["BILL_AMT1"],
    0
    )

In [22]:
risk[["PAY_RATIO_LATEST", "default.payment.next.month"]].corr()

                            PAY_RATIO_LATEST  default.payment.next.month
PAY_RATIO_LATEST                    1.000000                   -0.006024
default.payment.next.month         -0.006024                    1.000000

In [28]:
pay_cols = ["PAY_AMT1", "PAY_AMT2", "PAY_AMT3", "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"]
bill_cols = ["BILL_AMT1", "BILL_AMT2", "BILL_AMT3", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6"]

ratios = risk[pay_cols].values / risk[bill_cols].values
ratios = np.nan_to_num(ratios, nan=0.0, posinf=0.0, neginf=0.0)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10300\124428043.py:4: RuntimeWarning: divide by zero encountered in divide
  ratios = risk[pay_cols].values / risk[bill_cols].values
C:\Users\Admin\AppData\Local\Temp\ipykernel_10300\124428043.py:4: RuntimeWarning: invalid value encountered in divide
  ratios = risk[pay_cols].values / risk[bill_cols].values

In [29]:
risk["PAY_RATIO_MEAN"] = ratios.mean(axis=1)

In [30]:
risk[["PAY_RATIO_MEAN", "default.payment.next.month"]].corr()

                            PAY_RATIO_MEAN  default.payment.next.month
PAY_RATIO_MEAN                      1.0000                      0.0031
default.payment.next.month          0.0031                      1.0000

In [32]:
ratios = risk[pay_cols].values / risk[bill_cols].values
ratios[risk[bill_cols].values <= 0] = np.nan
risk["PAY_RATIO_MEAN"] = np.nanmean(ratios, axis=1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10300\4154693531.py:1: RuntimeWarning: divide by zero encountered in divide
  ratios = risk[pay_cols].values / risk[bill_cols].values
C:\Users\Admin\AppData\Local\Temp\ipykernel_10300\4154693531.py:1: RuntimeWarning: invalid value encountered in divide
  ratios = risk[pay_cols].values / risk[bill_cols].values
C:\Users\Admin\AppData\Local\Temp\ipykernel_10300\4154693531.py:3: RuntimeWarning: Mean of empty slice
  risk["PAY_RATIO_MEAN"] = np.nanmean(ratios, axis=1)

In [33]:
risk[["PAY_RATIO_MEAN", "default.payment.next.month"]].corr()

                            PAY_RATIO_MEAN  default.payment.next.month
PAY_RATIO_MEAN                     1.00000                    -0.01079
default.payment.next.month        -0.01079                     1.00000

### PROP MONTHS LOW PAYMENT

In [38]:
low_payment = ratios < 0.5
low_payment = low_payment.astype(int)
valid_months = ~np.isnan(ratios)

In [39]:
risk["PROP_MONTHS_LOW_PAYMENT"] = (
    low_payment.sum(axis=1) /
    valid_months.sum(axis=1)
)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10300\3156822121.py:2: RuntimeWarning: invalid value encountered in divide
  low_payment.sum(axis=1) /

In [40]:
risk[["PROP_MONTHS_LOW_PAYMENT", "default.payment.next.month"]].corr()

,PROP_MONTHS_LOW_PAYMENT,default.payment.next.month
PROP_MONTHS_LOW_PAYMENT,1.000000,0.108628
default.payment.next.month,0.108628,1.000000

### PROP_MONTHS_ZERO_PAYMENT

In [41]:
zero_payment = (risk[pay_cols].values == 0) & (risk[bill_cols].values > 0)
risk["PROP_MONTHS_ZERO_PAYMENT"] = (zero_payment.sum(axis=1)) / (valid_months.sum(axis=1))

C:\Users\Admin\AppData\Local\Temp\ipykernel_10300\1275379255.py:2: RuntimeWarning: invalid value encountered in divide
  risk["PROP_MONTHS_ZERO_PAYMENT"] = (zero_payment.sum(axis=1)) / (valid_months.sum(axis=1))

In [42]:
risk[["PROP_MONTHS_ZERO_PAYMENT", "default.payment.next.month"]].corr()

,PROP_MONTHS_ZERO_PAYMENT,default.payment.next.month
PROP_MONTHS_ZERO_PAYMENT,1.000000,0.159189
default.payment.next.month,0.159189,1.000000

### PROPORTION OF MONTHS WITH OVERPAYMENT

In [45]:
over_payment = ratios > 1

risk["PROP_MONTHS_OVERPAYMENT"] = (
    over_payment.sum(axis=1) /
    valid_months.sum(axis=1)
)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10300\1097155452.py:4: RuntimeWarning: invalid value encountered in divide
  over_payment.sum(axis=1) /

In [46]:
risk[["PROP_MONTHS_OVERPAYMENT", "default.payment.next.month"]].corr()

,PROP_MONTHS_OVERPAYMENT,default.payment.next.month
PROP_MONTHS_OVERPAYMENT,1.000000,-0.111428
default.payment.next.month,-0.111428,1.000000

### PAY_DISCIPLINE_SCORE

In [47]:
risk["PAY_DISCIPLINE_SCORE"] = (
    1.0 * risk["PROP_MONTHS_OVERPAYMENT"]
    - 1.0 * risk["PROP_MONTHS_LOW_PAYMENT"]
    - 1.5 * risk["PROP_MONTHS_ZERO_PAYMENT"]
)

In [48]:
risk[["PAY_DISCIPLINE_SCORE", "default.payment.next.month"]].corr()

                            PAY_DISCIPLINE_SCORE  default.payment.next.month
PAY_DISCIPLINE_SCORE                    1.000000                   -0.180528
default.payment.next.month             -0.180528                    1.000000