In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns

In [2]:
risk = pd.read_csv("../data/UCI_Credit_Card.csv")
risk.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

### PAY LATEST

In [5]:
risk["PAY_LATEST"] = risk["PAY_0"]

In [6]:
risk[["PAY_LATEST", "default.payment.next.month"]].head()

   PAY_LATEST  default.payment.next.month
0           2                           1
1          -1                           1
2           0                           0
3           0                           0
4          -1                           0

In [7]:
risk[["PAY_LATEST", "default.payment.next.month"]].corr()

                            PAY_LATEST  default.payment.next.month
PAY_LATEST                    1.000000                    0.324794
default.payment.next.month    0.324794                    1.000000

### PAY MEAN

In [8]:
risk["PAY_MEAN"] = risk[["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]].mean(axis=1)

In [9]:
risk[["PAY_MEAN", "default.payment.next.month"]].head()

   PAY_MEAN  default.payment.next.month
0 -0.333333                           1
1  0.500000                           1
2  0.000000                           0
3  0.000000                           0
4 -0.333333                           0

In [10]:
risk[["PAY_MEAN", "default.payment.next.month"]].corr()

                            PAY_MEAN  default.payment.next.month
PAY_MEAN                    1.000000                    0.281955
default.payment.next.month  0.281955                    1.000000

### PAY MAX DELAY

In [12]:
risk["PAY_MAX_DELAY"] = risk[["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]].max(axis=1)
risk[["PAY_MAX_DELAY", "default.payment.next.month"]].head()

   PAY_MAX_DELAY  default.payment.next.month
0              2                           1
1              2                           1
2              0                           0
3              0                           0
4              0                           0

In [13]:
risk[["PAY_MAX_DELAY", "default.payment.next.month"]].corr()

                            PAY_MAX_DELAY  default.payment.next.month
PAY_MAX_DELAY                    1.000000                    0.331036
default.payment.next.month       0.331036                    1.000000