In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, roc_curve

RANDOM_STATE = 42

In [4]:
risk = pd.read_csv("../data/UCI_Credit_Card.csv")
risk.head()

   ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default.payment.next.month
0   1    20000.0    2  ...       0.0       0.0                           1
1   2   120000.0    2  ...       0.0    2000.0                           1
2   3    90000.0    2  ...    1000.0    5000.0                           0
3   4    50000.0    2  ...    1069.0    1000.0                           0
4   5    50000.0    1  ...     689.0     679.0                           0

[5 rows x 25 columns]

In [5]:
# Target
y = risk["default.payment.next.month"]

# Features (excluding ID and target)
X = risk.drop(columns=["ID", "default.payment.next.month"])

### Train/Test Split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=RANDOM_STATE)

In [9]:
print("Train default rate", y_train.mean())
print("Test default rate", y_test.mean())

Train default rate 0.22179166666666666
Test default rate 0.21883333333333332

In [10]:
X_train.head()

       LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6
21753    80000.0    2          2  ...    1218.0    1445.0     878.0
251      30000.0    1          2  ...     955.0       0.0       0.0
22941   180000.0    2          5  ...    6881.0   10340.0     182.0
618      60000.0    1          1  ...    1500.0    1900.0    2000.0
17090   130000.0    2          2  ...    5000.0    5000.0   10700.0

[5 rows x 23 columns]